# Блок 1: Редирект с HTTP на HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name deliveryotpechi.ru www.deliveryotpechi.ru;

    return 301 https://deliveryotpechi.ru$request_uri;
}

# Блок 2: Основная работа по HTTPS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name deliveryotpechi.ru www.deliveryotpechi.ru;

    root /var/www/public;
    index index.php index.html;

    # Пути к SSL сертификатам (которые мы пробросили через Docker)
    ssl_certificate /etc/letsencrypt/live/deliveryotpechi.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/deliveryotpechi.ru/privkey.pem;

    # Настройки безопасности SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Логи (полезно для отладки)
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}
